apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: m-caj-mono-backend
spec:
  podMetricsEndpoints:
    - interval: 10s
      path: /actuator/prometheus
      port: http
      scheme: http
  selector:
    matchLabels:
      app: m-caj-mono-backend