kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  config.json: >
    {"masterfileURL":"https://m-caj-masterfile-{{ .Values.project }}.{{ .Values.clusterAppsDomain }}","reservationURL":"https://m-caj-reservation-{{ .Values.project }}.{{ .Values.clusterAppsDomain }}","scheduleURL":"https://m-caj-schedule-{{ .Values.project }}.{{ .Values.clusterAppsDomain }}"}
