kind: Service
apiVersion: v1
metadata:
  name: m-caj-schedule
  labels:
    app: m-caj-schedule
    service: m-caj-schedule
spec:
  selector:
    app: m-caj-schedule
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http