kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: m-caj-masterfile
spec:
  host: m-caj-masterfile-{{ .Values.project }}.{{ .Values.clusterAppsDomain }}
  to:
    kind: Service
    name: m-caj-masterfile
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None